### ISSUE TITLE
Code Will Not Compile in VS2019

### ISSUE THREAD

**Issue by FireStorm5552** [ameerabdallah/Path_Finder_Cross#4]
I don't know if this is an issue with my install of Visual Studio, but when I try to compile, I get 4 unresolved errors. If this is an issue with my setup, please let me know so I can get to work.

![Capture](https://user-images.githubusercontent.com/16807855/69509731-fd209e00-0eee-11ea-9975-6365d286b183.PNG)

**Comment by ameerabdallah** [comment]
When you cloned the repository, did you make sure to copy the src folder in
the main repository directory over to the project folder? There is a src
folder in the project folder that needs to be updated manually with the new
src files any time you clone the repository
